annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: New Relic
  catalog.cattle.io/namespace: newrelic
  catalog.cattle.io/release-name: newrelic-bundle
apiVersion: v2
dependencies:
- condition: ksm.enabled
  name: kube-state-metrics
  repository: file://./charts/kube-state-metrics
- condition: newrelic-infra-operator.enabled
  name: newrelic-infra-operator
  repository: file://./charts/newrelic-infra-operator
- condition: infrastructure.enabled
  name: newrelic-infrastructure
  repository: file://./charts/newrelic-infrastructure
- condition: metrics-adapter.enabled
  name: newrelic-k8s-metrics-adapter
  repository: file://./charts/newrelic-k8s-metrics-adapter
- condition: logging.enabled
  name: newrelic-logging
  repository: file://./charts/newrelic-logging
- condition: newrelic-pixie.enabled
  name: newrelic-pixie
  repository: file://./charts/newrelic-pixie
- condition: kubeEvents.enabled
  name: nri-kube-events
  repository: file://./charts/nri-kube-events
- condition: webhook.enabled
  name: nri-metadata-injection
  repository: file://./charts/nri-metadata-injection
- condition: prometheus.enabled
  name: nri-prometheus
  repository: file://./charts/nri-prometheus
- alias: pixie-chart
  condition: pixie-chart.enabled
  name: pixie-operator-chart
  repository: file://./charts/pixie-operator-chart
- condition: pixie-operator-helm2-chart.enabled
  name: pixie-operator-helm2-chart
  repository: file://./charts/pixie-operator-helm2-chart
description: A chart groups together the individual charts for the New Relic Kubernetes
  solution for more comfortable deployment.
home: https://github.com/newrelic/helm-charts
icon: https://newrelic.com/themes/custom/curio/assets/mediakit/new_relic_logo_vertical.png
keywords:
- infrastructure
- newrelic
- monitoring
kubeVersion: 1.16 - 1.22
maintainers:
- name: alvarocabanas
  url: https://github.com/alvarocabanas
- name: carlossscastro
  url: https://github.com/carlossscastro
- name: sigilioso
  url: https://github.com/sigilioso
- name: gsanchezgavier
  url: https://github.com/gsanchezgavier
- name: kang-makes
  url: https://github.com/kang-makes
- name: marcsanmi
  url: https://github.com/marcsanmi
- name: paologallinaharbur
  url: https://github.com/paologallinaharbur
- name: roobre
  url: https://github.com/roobre
name: nri-bundle
sources:
- https://github.com/newrelic/nri-bundle/
- https://github.com/newrelic/nri-bundle/tree/master/charts/nri-bundle
- https://github.com/newrelic/nri-kubernetes/tree/master/charts/newrelic-infrastructure
- https://github.com/newrelic/nri-prometheus/tree/master/charts/nri-prometheus
- https://github.com/newrelic/k8s-metadata-injection/tree/master/charts/nri-metadata-injection
- https://github.com/newrelic/newrelic-k8s-metrics-adapter/tree/master/charts/newrelic-k8s-metrics-adapter
- https://github.com/newrelic/nri-kube-events/tree/master/charts/nri-kube-events
- https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-logging
- https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-pixie
- https://github.com/newrelic/newrelic-infra-operator/tree/master/charts/newrelic-infra-operator
version: 4.3.200
