apiVersion: v2
description: Provides helpers to provide consistency on all the charts
keywords:
- newrelic
- chart-library
maintainers:
- name: alvarocabanas
  url: https://github.com/alvarocabanas
- name: carlossscastro
  url: https://github.com/carlossscastro
- name: gsanchezgavier
  url: https://github.com/gsanchezgavier
- name: kang-makes
  url: https://github.com/kang-makes
- name: marcsanmi
  url: https://github.com/marcsanmi
- name: paologallinaharbur
  url: https://github.com/paologallinaharbur
- name: roobre
  url: https://github.com/roobre
- name: sigilioso
  url: https://github.com/sigilioso
name: common-library
type: library
version: 1.0.2
